on:
  workflow_call:
    secrets:
      env:
      POSTGRES_DB_HOST:
        required: true
      POSTGRES_DB_USER:
        required: true
      POSTGRES_DB_PASSWORD:
        required: true
      POSTGRES_DB_DATABASE:
        required: true
  
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: create env file
        run: |
          touch packages/bff/.env
          echo POSTGRES_DB_HOST=${{ secrets.POSTGRES_DB_HOST }} >> packages/bff/.env
          echo POSTGRES_DB_USER=${{ secrets.POSTGRES_DB_USER }} >> packages/bff/.env
          echo POSTGRES_DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }} >> packages/bff/.env
          echo POSTGRES_DB_DATABASE=${{ secrets.POSTGRES_DB_DATABASE }} >> packages/bff/.env
      - name: Build UI
        run: cd packages/ui && npm run build -- --env APP_ENV=production
      - name: Build BFF
        run: cd packages/bff && npm run compile
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      # https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-cli
      - name: Upload UI to Azure Blob Storage
        run: az storage blob upload --account-name <storage-account> --container-name <container> --name ui-mfe.js --file packages/ui/dist/ --auth-mode login
      # https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=openid%2Cnodejs
      - name: Deploy BFF to Azure App Service
        run: |
          cd packages/bff
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory:  my-app-path

      # deploy web app using Azure credentials
      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Azure logout 
      - name: logout
        run: |
          az logout
