name: "Merge to main branch"

permissions:
  id-token: write
  contents: read


env:
  AZURE_WEBAPP_NAME: family-album-mfe   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'packages/bff'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'   

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  init:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Azure Login
        uses: azure/login@v2
        with:
          # https://github.com/Azure/login?tab=readme-ov-file#login-with-a-service-principal-secret
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      - name: Azure CLI script file
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/init.sh
            $GITHUB_WORKSPACE/init.sh
  run-tests:
    name: Lint, unit tests and audit
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: UI lint, unit tests and audit
        run: cd packages/ui && npm run lint && npm run unit
      - name: BFF lint, unit tests and audit
        run: cd packages/bff && npm run lint && npm run unit

  deploy:
    name: Development environment
    needs: [init, run-tests]
    uses: ./.github/workflows/deploy.yml
    secrets:
      POSTGRES_DB_HOST: ${{ secrets.POSTGRES_DB_HOST }}
      POSTGRES_DB_USER: ${{ secrets.POSTGRES_DB_USER }}
      POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
      POSTGRES_DB_DATABASE: ${{ secrets.POSTGRES_DB_DATABASE }}

  FUNCTIONAL_TEST:
    name: Functional test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
    needs: [deploy]
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          working-directory: packages/functional
          browser: chrome
          record: true
          parallel: true
